<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mydemodistribution"
 *
 * Auto generated by Extension Builder 2018-04-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'My Distribution',
    'description' => '',
    'category' => 'distribution',
    'author' => 'Cai He',
    'author_email' => 'hecai2222@hotmail.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
            'version' =>'',
            'recycler' =>'',
            'filemetadata' =>'',
            'powermail' =>'',
            'realurl' =>'',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
